backend/AppWeb/accounts/urls.py
from django.urls import include, path
from django.contrib.auth.forms import SetPasswordForm, PasswordResetForm
from django.contrib.auth.views import (password_reset_complete, password_reset_confirm,
                                       password_reset_done, password_reset, login, logout)
from rest_framework.routers import DefaultRouter

from . import api, views, forms

app_name = 'accounts'

router = DefaultRouter()
apipatterns = router.urls + [
    path('registration/', api.CreateUserView.as_view()),
    path('users/me/', api.current_user),
#    path('users/me/update/<int:pk>', api.UpdateUserView.as_view())
]

password_reset_patterns = [
    path('done/', password_reset_complete, {
        'template_name': 'accounts/password/password_reset_complete.html',
        'extra_context': {
            'title': 'Password reset complete',
        }
    }, name='password_reset_complete'),
    path('reset/done/', password_reset_done, {
        'template_name': 'accounts/password/password_reset_done.html',
        'extra_context': {
            'title': 'Password reset done',
        }
    }, name='password_reset_done'),    
    path('reset/<uidb64>/<token>/', password_reset_confirm, {
        'set_password_form': SetPasswordForm,
        'template_name': 'accounts/password/password_reset_confirm.html',
        'post_reset_redirect': '/accounts/password/done/',
        'extra_context': {
            'title': 'Password reset confirm',
        }
    }, name='password_reset_confirm'),
    path('reset/', password_reset, {
        'password_reset_form': PasswordResetForm,
        'template_name': 'accounts/password/password_reset_form.html',
        'email_template_name': 'accounts/email/email_reset.html',
        'post_reset_redirect': '/accounts/password/reset/done/',
        'extra_context': {
            'title': 'Password Reset',
        }
    }, name='password_reset'),
]

profile_patterns = [
    path('login/', login, {'template_name': 'accounts/login.html', 
        'authentication_form': forms.CustomAuthenticationForm}, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', views.signup, name='signup')
]

urlpatterns = [
    path('', include(profile_patterns)),
    path('api/', include(apipatterns)),
    path('password/', include(password_reset_patterns)),
]

backend/AppWeb/sales/urls.py
from . import api
from rest_framework.routers import DefaultRouter
from django.urls import include, path

app_name = 'sales'

router = DefaultRouter()
router.register(r'products', api.ProductViewSet)
router.register(r'orders', api.OrderViewSet)

apipatterns = router.urls

urlpatterns = [    
    path('api/', include(apipatterns)),
    ]

backend/AppWeb/accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .helpers import profile_image_path

class Profile(models.Model):
    """An extension of user model."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=profile_image_path,
                               default='defaults/img/default-user.png')
    phone = models.CharField(_('telephone'), max_length=12, blank=True, null=True)
    #created_at = models.DateTimeField(auto_now_add=True)
    #updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username's name."""
        return f'{self.user.username} profile'

backend/AppWeb/accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from .models import Profile

class SignupForm(forms.ModelForm):
    """Create user form."""

    class Meta:
        """Signup form meta data."""

        model = User
        fields = ('first_name', 'email', 'password',)

    def __init__(self, *args, **kwargs):
        """Set required and widgets for fields."""
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['password'].widget = forms.PasswordInput()        

        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )

    
    def clean_email(self):
        """Validate if email is already used by other user."""
        email = self.cleaned_data['email'].lower()
        if User.objects.filter(email__iexact=email).exists():
            raise ValidationError(_('A user with that email already exists.'))
        return email

    def clean_password(self):
        """Validate password with settings constraints."""
        password = self.cleaned_data.get('password')
        password_validation.validate_password(self.cleaned_data.get('password'), self.instance)
        return password

    def save(self, commit=True):
        """Set email and password for new user."""
        user = super(SignupForm, self).save(commit=False)
        user.email = self.cleaned_data.get('email')
        user.username = self.cleaned_data.get('email')
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    """Create profile form."""

    class Meta:
        """profile form meta data."""
        model = Profile
        fields = ('phone',)

    def __init__(self, *args, **kwargs):
        """Set required and widgets for fields."""
        super(ProfileForm, self).__init__(*args, **kwargs)        
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )
            

class CustomAuthenticationForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        """Set required and widgets for fields."""
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )

backend/AppWeb/accounts/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import ugettext as _

from . import forms, utils


def signup(request):
    """Display and handle the registration form."""
    if request.method == 'POST':
        form = forms.SignupForm(request.POST)
        form_profile = forms.ProfileForm(request.POST)
        if form.is_valid() and form_profile.is_valid():
            user = form.save()
            #Set user profile data 
            user_profile_id = user.profile.id           
            user.profile = form_profile.save(commit=False)
            user.profile.id = user_profile_id
            user.profile.save()
            
            # Authenticating 
            username = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)

            login(request, user)
            utils.send_welcome_email(request, user)
            return redirect(reverse(settings.LOGIN_REDIRECT_URL))
    else:
        form = forms.SignupForm()
        form_profile = forms.ProfileForm()

    page = {
        'title': _('Signup'),
    }

    context = {
        'form': form,
        'form_profile': form_profile,
        'page': page
    }
    return render(request, 'accounts/signup.html', context)

# def message(request, code):
#     if code == 'password_reset':
#         message = _(
#             '<strong>We have sent you an email!</strong> Please, follow the instructions to reset your password.')
#         # messages.add_message(request, messages.INFO, message)
#         return render(request, 'accounts/echo.html', locals())
#         # return redirect(reverse('accounts:password_reset'))
# 
#     if code == 'password_reset_confirm':
#         messages.add_message(request, messages.INFO, _(
#             '<strong>Success!</strong> You have changed your password.'))
#         return redirect(reverse('accounts:login'))
# 
#     if code == 'password_change_done':
#         messages.add_message(request, messages.INFO, _(
#             '<strong>Success!</strong> You have changed your password.'))
#         return redirect(reverse('accounts:password_change'))
# 
#     return redirect(reverse('accounts:profile_edit'))

backend/AppWeb/accounts/templates/accounts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{page.title}}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/styles.css' %}">
</head>
<body class="accounts-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<img src="{% static 'accounts/img/logo.jpg' %}">
					</div>
	{%block content%}
	{%endblock%}
					<div class="footer">
						Copyright &copy; 2018 &mdash; Atix Plus 
					</div>
				</div>
			</div>
		</div>
	</section>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
	{%block scripts%}
	{%endblock%}
</body>
</html>

backend/AppWeb/accounts/templates/accounts/login.html
{% extends 'accounts/layout.html' %}
{% load i18n %}

{% block content %}
{% if request.user.is_authenticated %}
{% trans 'You are logged like ' %}
    <b>{{ user.username }}</b>, <a href="{% url 'accounts:logout' %}">logout ?</a>
{% else %}
<div class="card fat">
    <div class="card-body">
      <h4 class="card-title">Login</h4>              
        <form action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}            
            {% for field in form %}
            <div class="form-group">
              <label for="id_{{field.name}}">{{field.label}}</label>
              {{field}}
              <small id="id_{{field.name}}_help" class="form-text text-muted">{{field.help_text}}</small>
            </div>
            {% endfor %}

            <div class="form-group no-margin">
              <button type="submit" class="btn btn-primary btn-block">
                Ingresar
              </button>
            </div>
            <br>
        <div class="margin-top20 text-center">                    
          <a class="font-semi-bold" href="{% url 'accounts:password_reset' %}">¿Olvidaste tu contraseña noob?</a>
        </div>
        <div class="margin-top20 text-center">
          ¿Eres nuevo?,
          <a class="font-semi-bold" href="{% url 'accounts:signup'%}">registrate</a>
        </div>
        </form>
    </div>
</div>
{% endif %}
</body>

{% endblock %}

backend/AppWeb/accounts/templates/accounts/signup.html
{% extends 'accounts/layout.html' %}
{% load i18n %}

{% block content %}

  {% if request.user.is_authenticated %}
    {% trans 'You are logged like ' %}
    <b>{{ user.username }}</b>, <a href="{% url 'accounts:logout' %}">logout ?</a>
  {% else %}  

<div class="card fat">
  <div class="card-body">
    <h4 class="card-title">Registrate</h4>              
      <form method="post" action=".">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group">
          <label for="id_{{field.name}}">{{field.label}}</label>
          {{field}}
          <small id="id_{{field.name}}_help" class="form-text text-muted">{{field.help_text}}</small>
        </div>
        {% endfor %}

        {% for field in form_profile %}
        <div class="form-group">
          <label for="id_{{field.name}}">{{field.label}}</label>
          {{field}}
          <small id="id_{{field.name}}_help" class="form-text text-muted">{{field.help_text}}</small>
        </div>
        {% endfor %}

        <div class="form-group no-margin">
          <button type="submit" class="btn btn-primary btn-block">
            Registrate
          </button>
        </div>
        <div class="margin-top20 text-center">
          ¿Ya tienes una cuenta?
          <a class="font-semi-bold" href="{% url 'accounts:login'%}">Iniciar sesión</a>
        </div>
      </form>
    </div>
  </div>
  {% endif %}
{% endblock %}